/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.connection;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vugia
 */
public class Taikhoan extends javax.swing.JFrame {

    /**
     * Creates new form Taikhoan
     */
    public Taikhoan() {
        initComponents();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        txt_user = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_taikhoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_quequan = new javax.swing.JTextField();
        btn_xoa = new javax.swing.JButton();
        btn_capnhat = new javax.swing.JButton();
        btn_dangxuat = new javax.swing.JButton();
        txt_timkiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_chucvu = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        table_taikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_taikhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_taikhoan);

        jLabel2.setText("Pass");

        jLabel3.setText("Họ tên");

        jLabel4.setText("SĐT");

        jLabel5.setText("Quê quán");

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });

        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });

        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });

        txt_quequan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quequanActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_capnhat.setText("Cập nhật");
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });

        btn_timkiem.setText("Tìm kiếm ");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("QUẢN LÝ TÀI KHOẢN");

        jLabel7.setText("Chức vụ");

        txt_chucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chucvuActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        d.setText("ID");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_timkiem)
                        .addGap(62, 62, 62)
                        .addComponent(btn_timkiem)
                        .addGap(341, 341, 341))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addGap(35, 35, 35)
                        .addComponent(btn_capnhat)
                        .addGap(36, 36, 36)
                        .addComponent(btn_xoa)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_dangxuat)
                        .addGap(339, 339, 339))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(d))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoa)
                    .addComponent(btn_them)
                    .addComponent(btn_capnhat)
                    .addComponent(btn_dangxuat)
                    .addComponent(jButton1))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void txt_quequanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quequanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quequanActionPerformed

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String timkiem = txt_timkiem.getText();
        String user = txt_user.getText();
        Connection con = connection.getConnection();
        try {
                    //b2: tạo đối tượng statement để thực hiện truy vấn
            String sql = "select * from user where username like '"+timkiem+"'" ;
            Statement st = con.createStatement();
            
            //b3: tạo đối tượng resultset để lưu kq từ statement
            ResultSet rs = st.executeQuery(sql);
//            table_taikhoan.removeAll();
             String[] rowhead={"ID","User","Password","Phan quyen","Họ tên","Số điẹn thoại","Quê quán"};
            DefaultTableModel tb = new DefaultTableModel(rowhead,0);
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                
                tb.addRow(v);
            }
            table_taikhoan.setModel(tb);
              st.close();
            con.close();
            txt_timkiem.setText("");
        }
        catch(Exception e){}
    }//GEN-LAST:event_btn_timkiemActionPerformed
private boolean check_numeric() {
        String sdt;
        String regex = "[0-9]+[\\.]?[0-9]*";
       
         sdt=txt_sdt.getText();
        if(Pattern.matches(regex, sdt)) {
            if(Integer.parseInt(sdt)>100) {
                return true;
            }
            else {
                return false;
            }
        }
        else {
            return true;
        }
    }
private void check_valid(String ms) {
        try {
            String id = txt_id.getText();
            String valid="";
            Connection con = connection.getConnection();
            
            String sqlQuery="Select * from user where id='"+ms+"'";
            Statement st=con.createStatement();
            
            ResultSet rs=st.executeQuery(sqlQuery);
            while(rs.next()) {
                valid = rs.getString(1);
            }
            if(valid.length()!=0) {
                JOptionPane.showMessageDialog(this, "Trùng khóa");
                return;
            }
        } catch (Exception e) {
        }
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        
     String id = txt_id.getText();
     String hoten = txt_hoten.getText();
     String user = txt_user.getText();
     String pass = txt_pass.getText();
     String sdt = txt_sdt.getText();
     String quequan = txt_quequan.getText();
     String chucvu = txt_chucvu.getText();
        check_valid(id);
      check_valid(user);
     if(hoten.isEmpty()||user.isEmpty()||pass.isEmpty()||sdt.isEmpty()||quequan.isEmpty()||chucvu.isEmpty()||id.isEmpty()||check_numeric()){
     
      JOptionPane.showMessageDialog(null, "Điền vào trường còn trống hoặc kiểm tra lại định dạng dữ liệu ! ");
      
     }
     else {
     try {
         if(chucvu.equals("hocsinh")||chucvu.equals("giaovien")) {
        Connection con = connection.getConnection();
        String sql = "insert into user  values('"+id+"','"+user+"','"+pass+"','"+chucvu+"',N'"+hoten+"','"+sdt+"',N'"+quequan+"')";
             Statement st = null;
           
                st = con.createStatement();
             st.executeUpdate(sql);
           
           JOptionPane.showMessageDialog(null, "Thêm thành công ! ");
           load_table();
           txt_chucvu.setText("");
           txt_hoten.setText("");
           txt_id.setText("");
           txt_pass.setText("");
           txt_quequan.setText("");
           txt_sdt.setText("");
           txt_user.setText("");
         }
         else {
         JOptionPane.showMessageDialog(null, " kiểm tra lại định dạng dữ liệu của chức vụ ! ");
         }
     }
     catch(Exception e ) {}
     
     }
    }//GEN-LAST:event_btn_themActionPerformed

    private void txt_chucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chucvuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chucvuActionPerformed
    public static void clearAllTextFields(Container container) {
  for (Component component : container.getComponents()) {
    if (component instanceof JTextField) {
      ((JTextField) component).setText("");
    }
  }
}

// ... (in your button action listener)

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void table_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_taikhoanMouseClicked
        // TODO add your handling code here:
         int i = table_taikhoan.getSelectedRow();
        DefaultTableModel tb = (DefaultTableModel)table_taikhoan.getModel();
        txt_id.setText(tb.getValueAt(i, 0).toString());
        txt_user.setText(tb.getValueAt(i, 1).toString());
        txt_pass.setText(tb.getValueAt(i, 2).toString());
        txt_chucvu.setText(tb.getValueAt(i, 3).toString());
        txt_hoten.setText(tb.getValueAt(i, 4).toString());
        txt_sdt.setText(tb.getValueAt(i, 5).toString());
        txt_quequan.setText(tb.getValueAt(i, 6).toString());
        txt_id.setEnabled(false);
        txt_user.setEnabled(false);
    }//GEN-LAST:event_table_taikhoanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txt_chucvu.setText("");
           txt_hoten.setText("");
           txt_id.setText("");
           txt_pass.setText("");
           txt_quequan.setText("");
           txt_sdt.setText("");
           txt_user.setText("");
           txt_id.setEnabled(true);
           txt_user.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
         String id = txt_id.getText();
     String hoten = txt_hoten.getText();
     String user = txt_user.getText();
     String pass = txt_pass.getText();
     String sdt = txt_sdt.getText();
     String quequan = txt_quequan.getText();
     String chucvu = txt_chucvu.getText();
       
     if(hoten.isEmpty()||user.isEmpty()||pass.isEmpty()||sdt.isEmpty()||quequan.isEmpty()||chucvu.isEmpty()){
     
      JOptionPane.showMessageDialog(null, "Điền vào trường còn trống hoặc kiểm tra lại định dạng dữ liệu ! ");
      
     }
     else {
        
     try {
         if(chucvu.equals("hocsinh")||chucvu.equals("giaovien")) {
        Connection con = connection.getConnection();
        String sql = "update user set username = '"+user+"' , password  ='"+pass+"',phanquyen = '"+chucvu+"',hoten =  '"+hoten+"',sdt = '"+sdt+"',quequan = '"+quequan+"' where id = '"+id+"' ";
             Statement st = null;
           
                st = con.createStatement();
             st.executeUpdate(sql);
             
           JOptionPane.showMessageDialog(null, "Cập nhật thành công");
           load_table();
           txt_chucvu.setText("");
           txt_hoten.setText("");
           txt_id.setText("");
           txt_pass.setText("");
           txt_quequan.setText("");
           txt_sdt.setText("");
           txt_user.setText("");
         }
         else {
         JOptionPane.showMessageDialog(null, " kiểm tra lại định dạng dữ liệu của chức vụ ! ");
         }
     }
     catch(Exception e ) {}
     
     }
                                  
        
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        String id = txt_id.getText();
        try {
             Connection con = connection.getConnection();
        String sql = "delete from user where id = '"+id+"' ";
             Statement st = null;
           
                st = con.createStatement();
             st.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "Xóa thành công");
           load_table();
        }
        catch (Exception e ) {}
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        // TODO add your handling code here:
        
        new View_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dangxuatActionPerformed
private void load_table() {
    try {
    Connection con = connection.getConnection();
    String sql = "select * from user WHERE phanquyen IN ('hocsinh','giaovien')";
            Statement st = con.createStatement();
            
            //b3: tạo đối tượng resultset để lưu kq từ statement
            ResultSet rs = st.executeQuery(sql);
            
            //b4: hiển thị lên jtable
//            Table1.removeAll();
            String[] rowhead={"ID","User","Password","Phan quyen","Họ tên","Số điẹn thoại","Quê quán"};
            DefaultTableModel tb = new DefaultTableModel(rowhead,0);
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                
                tb.addRow(v);
            }
            table_taikhoan.setModel(tb);
            
            //b5: đóng kết nối
            st.close();
            con.close();
}
    catch (Exception e ) {}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhat;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel d;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_taikhoan;
    private javax.swing.JTextField txt_chucvu;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_quequan;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
