/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import database.connection;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vugia
 */
public class View_CauHoi extends javax.swing.JFrame {

    /**
     * Creates new form View_CauHoi
     */
    Map<String, String> map_mamon = new HashMap<>();
    Map<String, String> map_mamon2 = new HashMap<>();
    public View_CauHoi() {
        initComponents();
    load_table();
        load_cbMamon();
        txtid.setEnabled(false);
    }
    Connection con ;
     private void load_table(){
        try{
            con= connection.getConnection();
            String sqlQueryGetSach="Select * from cauhoi";
            Statement st=con.createStatement();
            
            ResultSet rs=st.executeQuery(sqlQueryGetSach);
            
            tbcauhoi.removeAll();
            String[] rowhead={"ID Câu Hỏi","Môn Học","Đề Bài","Câu 1","Câu 2","Câu 3","Câu 4"};
            DefaultTableModel tb = new DefaultTableModel(rowhead,0);
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                tb.addRow(v);
            }
            tbcauhoi.setModel(tb);
            st.close();
            con.close();
        }catch(Exception e){  
        }
    }
    private void load_cbMamon(){
         try {
           con= connection.getConnection();
            String sqlQueryGetLoaiSach="Select * from monhoc";
            Statement st=con.createStatement();
     
            ResultSet rs=st.executeQuery(sqlQueryGetLoaiSach);
            
            while(rs.next()) {
                cbmamon.addItem(rs.getString("tenmon"));
                map_mamon.put(rs.getString("mamon"),rs.getString("tenmon"));
                map_mamon2.put(rs.getString("tenmon"),rs.getString("mamon"));
            }
            
            st.close();
            con.close();
            
        } catch (Exception e) {
            System.out.println("qlytacgia.jKT01.load_cbMaloai()");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcau1 = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcau2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcau3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcau4 = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcauhoi = new javax.swing.JTable();
        cbmamon = new javax.swing.JComboBox<>();
        txtdebai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Đáp án");

        jLabel5.setText("Câu 1");

        btnthem.setText("Thêm Mới");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel6.setText("Câu 2");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Câu 3");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Câu 4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Câu Hỏi Đề Thi");

        btntimkiem.setText("Tìm Kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Câu hỏi");

        jLabel3.setText("Mã Môn Học");

        txtcau3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcau3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Đề Bài");

        txtcau4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcau4ActionPerformed(evt);
            }
        });

        tbcauhoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Câu Hỏi", "Môn Học", "Đề Bài", "Câu 1", "Câu 2", "Câu 3", "Câu 4"
            }
        ));
        tbcauhoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcauhoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcauhoi);

        cbmamon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Môn Học", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(cbmamon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdebai, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcau1)
                                    .addComponent(txtcau2)
                                    .addComponent(txtcau3)
                                    .addComponent(txtcau4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnthem)
                .addGap(57, 57, 57)
                .addComponent(btnsua)
                .addGap(45, 45, 45)
                .addComponent(btnxoa)
                .addGap(61, 61, 61)
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntimkiem)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbmamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtdebai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtcau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcau3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcau4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        String mm,db,c1,c2,c3,c4;
        mm=map_mamon2.get(cbmamon.getSelectedItem().toString());
        db=txtdebai.getText();
        c1=txtcau1.getText();
        c2=txtcau2.getText();
        c3=txtcau3.getText();
        c4=txtcau4.getText();
        if(mm.isEmpty() || db.isEmpty() || c1.isEmpty() || c2.isEmpty() || c3.isEmpty() || c4.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Điền trường còn thiếu");
        }
        try {
            con = connection.getConnection();
            String sql = "INSERT INTO cauhoi(mamon,debai,dapan1,dapan2,dapan3,dapan4) VAlUES ('"+mm+"','"+db+"','"+c1+"','"+c2+"','"+c3+"','"+c4+"')";
            System.out.println(sql);
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Thêm thành công");

            load_table();
            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String id, mm,db,c1,c2,c3,c4;
        id = txtid.getText();
        mm=map_mamon2.get(cbmamon.getSelectedItem().toString());
        db=txtdebai.getText();
        c1=txtcau1.getText();
        c2=txtcau2.getText();
        c3=txtcau3.getText();
        c4=txtcau4.getText();
        try {
            con=connection.getConnection();
            String sql = "UPDATE cauhoi SET mamon=N'"+mm+"',debai=N'"+db+"',dapan1=N'"+c1+"',dapan2=N'"+c2+"',dapan3=N'"+c3+"',dapan4="+c4+" WHERE idcauhoi=N'"+id+"'";

            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            load_table();

            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String id;
        id=txtid.getText();

        try {
            con=connection.getConnection();
            String sql = "DELETE from cauhoi WHERE idcauhoi = '"+id+"'";
            System.out.println(sql);
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Xoá thành công");
            load_table();

            con.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        String id, mm = "";
        id = txttimkiem.getText();
        if("Chọn Môn Học".equals(cbmamon.getSelectedItem().toString())){
            mm="";
        }else{
            mm=map_mamon2.get(cbmamon.getSelectedItem().toString());
        }
        try {
            con=connection.getConnection();
            String sql = "SELECT * from cauhoi WHERE idcauhoi like '%"+id+"%' AND mamon like '%"+mm+"%' ";
            System.out.println(sql);
            Statement st=con.createStatement();

            ResultSet rs=st.executeQuery(sql);

            tbcauhoi.removeAll();
            String[] rowhead={"ID Câu Hỏi","Môn Học","Đề Bài","Câu 1","Câu 2","Câu 3","Câu 4"};
            DefaultTableModel tb = new DefaultTableModel(rowhead,0);
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                tb.addRow(v);
            }

            tbcauhoi.setModel(tb);
            st.close();
            con.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void txtcau3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcau3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcau3ActionPerformed

    private void txtcau4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcau4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcau4ActionPerformed

    private void tbcauhoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcauhoiMouseClicked
        // TODO add your handling code here:
        try {
            //
            int index=tbcauhoi.getSelectedRow();
            DefaultTableModel dtm=(DefaultTableModel) tbcauhoi.getModel();
            txtid.setText(dtm.getValueAt(index, 0).toString());
            cbmamon.setSelectedItem(map_mamon.get(dtm.getValueAt(index, 1).toString()));
            txtdebai.setText(dtm.getValueAt(index, 2).toString());
            txtcau1.setText(dtm.getValueAt(index, 3).toString());
            txtcau2.setText(dtm.getValueAt(index, 4).toString());
            txtcau3.setText(dtm.getValueAt(index, 5).toString());
            txtcau4.setText(dtm.getValueAt(index, 6).toString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tbcauhoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_CauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_CauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_CauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_CauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_CauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbmamon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbcauhoi;
    private javax.swing.JTextField txtcau1;
    private javax.swing.JTextField txtcau2;
    private javax.swing.JTextField txtcau3;
    private javax.swing.JTextField txtcau4;
    private javax.swing.JTextField txtdebai;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
